### ISSUE TITLE
Possible to modify for threading support?

### ISSUE THREAD

**Issue by Coffeeling** [adifyr/obsidian-chat-view#11]
Some kind of threaded/tree-like view would be wonderful for taking local hardcopy of threads on things like Twitter, Reddit, Hacker News etc.

**Comment by adifyr** [comment]
You may be able to achieve something of the sort upto 2 levels of nesting using the alignment of Chat Bubbles. Just set the width to 90% and align them according to their level of nesting. Take a look at the example below:

~~~
```chat
{mw=80}

< | Did you check out the new modding support on the software? I heard it was super cool! | Mbolly on Thursday at 7:34 PM
< | I don't really think this fits my use-case. I would rather go with InstaServe software seeing as they have better customization for the APIs they generate | Kilimango on Thursday at 8:12 PM
^ | InstaServe didn't really live up to it's promises for me. Yes, the customization is there. But, it's so buggy! | Gellet on Friday at 11:05 AM
^ | This! Gotta love InstaServe for its API Customization. I don't think there's any other product on the market that does this right now! | Foodoo on Friday at 12:59 PM
> | I'm sorry, are we forgetting about Linklet? They have the same level of customization as InstaServe. Yes, they're currently just in alpha, but the software is worth it! | Bennett on Friday at 2:02 PM
^ | I've been using InstaServe for about 8 months now. Never felt the need to migrate to a new software! | Croman on Friday at 4:23 PM
```
~~~

This will result in the below Chat View:

![image](https://user-images.githubusercontent.com/86793553/164964568-c159faf1-ae74-4e64-8d1d-32cd15af9523.png)

**I might come out with a minimal mode later for my plugin that removes the border and background so that the messages don't look like chat bubbles.** That being said, I do believe that a proper tree-view for forum threads is outside the purview of this plugin and would be more appropriately addressed in a plugin of their own.
