### ISSUE TITLE
Can't install latest update in Obsidian

### ISSUE THREAD

**Issue by GinoReiji** [adifyr/obsidian-chat-view#14]
At first it said "failed to install update" and stupidly I uninstall the plugin and now I can't install it at all. It kept saying "failed to install plugin" 😩

**Comment by menagerie198** [comment]
I managed to get it (v1.2.0)installed by downloading the three latest files (main.js, manifest.json, styles.css) into a folder I created called obsidian-chat-view.

**Comment by emory** [comment]
thanks for the suggestion @menagerie198 i'll follow suit and set a reminder to check back in a month or something.

**Comment by Sigbert11** [comment]
still have the initial install.   Since the 4 or 5 updates passed by which refused to install. Still the same BUG

<img width="364" alt="Screenshot of Obsidian" src="https://user-images.githubusercontent.com/84449137/198823144-925b1aaa-0455-4afb-8fcb-64c6f33f55f9.png">

**Comment by adifyr** [comment]
I'll take a look into this.

**Comment by adifyr** [comment]
I have published a new release `v1.2.1` for the plugin. Please try to reinstall and let me know if the issue persists.

Awaiting your feedback.

**Comment by emory** [comment]
> Please try to reinstall the plugin and let me know if the issue persists.

@adifyr i rm'ed on two workstations my local copy, HUP'ed Obsidian and it's running great so far! great job sorting that out!

a lot of my notes are MS Teams convos asynchronous and your plugin lets me make it really clear who says what. 

now i feel like i can safely take time to compose some templates or keysmith/textexpander incantations to make it easier to use because i mess up a lot 😂

**Comment by GinoReiji** [comment]
@adifyr It works now!!! Thank you so much 😊

**Comment by menagerie198** [comment]
Working just dandy here too. Cheers

**Comment by adifyr** [comment]
Great to hear it works now! Closing this issue...
Thanks for the feedback everyone!
